[package]
name = "avc2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wrapping_arithmetic = "0.1.0"
rand = "0.8.5"
